=== Sergi-P/Examen-Final-DDL/examen.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<xsd:element name="ExamenFinalDDL" type="examenFinalDDL" />
   <xsd:complexType name="examenFinalDDL">
      <xsd:complexContent>
         <xsd:restriction base="xsd:anyType">
            <xsd:sequence>
               <xsd:element name="Aspirante" type="TipoAspirante" />
               <xsd:element name="Fotos" type="Tipofotos" />

               <xsd:element name="Meritos" type="TipoMeritos" />
               <xsd:element name="tribunal" type="Tipotribunal" />
               <xsd:element name="Jueces" type="Tipojueces" maxOccurs="6"/>
               <xsd:element name="Criterio_Valoracion" type="TipoCriterio_Valoracion" />
               <xsd:element name="Cinturon_Negro_Cuarto_Dan" type="TipoCinturon_Negro_Cuarto_Dan" />
               <!-- 
               <xsd:element name="Cinturon_Negro_tercer_Dan" type="TipoCinturon_Negro_tercer_Dan" />
               <xsd:element name="Cinturon_Negro_segundo_Dan" type="TipoCinturon_Negro_segundo_Dan" />
               <xsd:element name="Cinturon_Negro_primer_Dan" type="TipoCinturon_Negro_primer_Dan" />
               <xsd:element name="cinturon_Negro" type="Tipocinturon_Negro" />
               <xsd:element name="Hasta_3er_Dan" type="TipoHasta_3er_Dan" />
               <xsd:element name="Quinto_Dan_y_Superior" type="TipoQuinto_Dan_y_Superior" />
               -->
               <xsd:element name="Suspende_Examen" type="TipoSuspende_Examen" />
            </xsd:sequence>
         </xsd:restriction>
      </xsd:complexContent>
   </xsd:complexType>



   <xsd:complexType name="TipoAspirante">
      <xsd:complexContent>
         <xsd:restriction base="xsd:anyType">
            <xsd:sequence>
               <xsd:element name="Id_Aspirante" type="tipoId" />
               <xsd:element name="Nombre" type="xsd:string" />
               <xsd:element name="Apellido" type="xsd:string" />
               <xsd:element name="DNI" type="tipodni" />
               <xsd:element name="Telefono" type="tipotelefono" />
               <xsd:element name="Direccion" type="xsd:string" />
               <xsd:element name="Fecha_Nacimiento" type="xsd:date" />
               <xsd:element name="Dan" type="xsd:string" />
               <xsd:element name="Cinturon" type="xsd:string" />
               <xsd:element name="Fecha_Ingreso" type="xsd:date" />
               <xsd:element name="Tiempo_Dan_Anterior" type="xsd:string" />
               <xsd:element name="Cuenta_Abonada" type="xsd:string" />
            </xsd:sequence>
         </xsd:restriction>
      </xsd:complexContent>
   </xsd:complexType>

   <xsd:simpleType name="tipoId">
      <xsd:restriction base="xsd:integer">
         <xsd:pattern value="[0-9]{3}"></xsd:pattern>
      </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="tipotelefono">
      <xsd:restriction base="xsd:integer">
         <xsd:pattern value="[0-9]{9}"></xsd:pattern>
      </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="tipodni">
      <xsd:restriction base="xsd:string">
         <xsd:pattern value="[0-9]{8}[a-z]{1}"></xsd:pattern>
      </xsd:restriction>
   </xsd:simpleType>

   <xsd:complexType name="Tipofotos">
      <xsd:complexContent>
         <xsd:restriction base="xsd:anyType">
            <xsd:sequence>
               <xsd:element name="Foto_Dni" type="xsd:string" />
               <xsd:element name="Foto_Carnet_Grado" type="xsd:string" />
               <xsd:element name="Foto_Aspirante" type="xsd:string" />
            </xsd:sequence>
         </xsd:restriction>
      </xsd:complexContent>
   </xsd:complexType>

   <xsd:complexType name="TipoMeritos">
      <xsd:complexContent>
         <xsd:restriction base="xsd:anyType">
            <xsd:sequence>
               <xsd:element name="Id_Aspirante" type="tipoIdM" />
               <xsd:element name="Edad_Aspirante" type="xsd:int" />
               <xsd:element name="Licencia_Actualizada" type="xsd:string" />
               <xsd:element name="Trabajo_Escrito" type="xsd:string" />
            </xsd:sequence>
         </xsd:restriction>
      </xsd:complexContent>
   </xsd:complexType>

   <xsd:simpleType name="tipoIdM">
      <xsd:restriction base="xsd:integer">
         <xsd:pattern value="[0-9]{3}"></xsd:pattern>
      </xsd:restriction>
   </xsd:simpleType>


   <xsd:complexType name="Tipotribunal">
      <xsd:complexContent>
         <xsd:restriction base="xsd:anyType">
            <xsd:sequence>
               <xsd:element name="Numero_Jueces" type="xsd:int" />
               <xsd:element name="Calificacion_Final" type="xsd:int" />
               <xsd:element name="Id_Aspirante" type="idAsp" />
               <xsd:element name="Resultado" type="xsd:string" />
               <xsd:element name="Dispensa_medica" type="xsd:string" />

            </xsd:sequence>
         </xsd:restriction>
      </xsd:complexContent>
   </xsd:complexType>
   <xsd:simpleType name="idAsp">
      <xsd:restriction base="xsd:integer">
         <xsd:pattern value="[0-9]{3}"></xsd:pattern>
      </xsd:restriction>
   </xsd:simpleType>

   <xsd:complexType name="Tipojueces">
      <xsd:complexContent>
         <xsd:restriction base="xsd:anyType">
            <xsd:sequence>
               <xsd:element name="id_Jueces" type="tipoIdJuez" />
               <xsd:element name="Nombre" type="xsd:string" />
               <xsd:element name="Apellido" type="xsd:string" />
               <xsd:element name="Diploma_Juez" type="xsd:string" />
            </xsd:sequence>
         </xsd:restriction>
      </xsd:complexContent>
   </xsd:complexType>

   <xsd:simpleType name="tipoIdJuez">
      <xsd:restriction base="xsd:integer">
         <xsd:pattern value="[0-9]{3}"></xsd:pattern>
      </xsd:restriction>
   </xsd:simpleType>


   

   <xsd:complexType name="TipoResultados">
      <xsd:complexContent>
         <xsd:restriction base="xsd:anyType">
            <xsd:sequence>
               <xsd:element name="Id_Aspirante" type="tipoIdR" />
               <xsd:element name="Resultado" type="xsd:boolean" />
            </xsd:sequence>
         </xsd:restriction>
      </xsd:complexContent>
   </xsd:complexType>

   <xsd:simpleType name="tipoIdR">
      <xsd:restriction base="xsd:integer">
         <xsd:pattern value="[0-9]{3}"></xsd:pattern>
      </xsd:restriction>
   </xsd:simpleType>





   <xsd:complexType name="TipoCriterio_Valoracion">
      <xsd:complexContent>
         <xsd:restriction base="xsd:anyType">
            <xsd:sequence>
               <xsd:element name="Indumentaria" type="xsd:int" />
               <xsd:element name="Aseo_Personal" type="xsd:int" />
               <xsd:element name="Ejecucion_Tecnica" type="xsd:int" />
               <xsd:element name="Valores" type="xsd:int" />
               <xsd:element name="Respuestas" type="xsd:int" />
            </xsd:sequence>
         </xsd:restriction>
      </xsd:complexContent>
   </xsd:complexType>

   <xsd:complexType name="TipoCinturon_Negro_Cuarto_Dan">
      <xsd:complexContent>
         <xsd:restriction base="xsd:anyType">
            <xsd:sequence>
               <xsd:element name="Kumite" type="xsd:string" />
               <xsd:element name="Kata" type="xsd:string" />
               <xsd:element name="Coloquio" type="xsd:string" />
               <xsd:element name="Aplicacion_Tecnica" type="xsd:string" />
               <xsd:element name="Demo_Libre" type="xsd:string" />
            </xsd:sequence>
         </xsd:restriction>
      </xsd:complexContent>
   </xsd:complexType>

   <xsd:complexType name="TipoCinturon_Negro_tercer_Dan">
      <xsd:complexContent>
         <xsd:restriction base="xsd:anyType">
            <xsd:sequence>
               <xsd:element name="Variaciones_tecnica" type="xsd:string" />
               <xsd:element name="Kumite" type="xsd:string" />
               <xsd:element name="Kata" type="xsd:string" />
               <xsd:element name="Aplicacion_Tecnica" type="xsd:string" />
               <xsd:element name="Teoria" type="xsd:string" />
               <xsd:element name="Campeonatos" type="xsd:string" />
               <xsd:element name="Tenica" type="xsd:string" />
               <xsd:element name="Aplicaciones" type="xsd:string" />
               <xsd:element name="Demo_Libre" type="xsd:string" />
            </xsd:sequence>
         </xsd:restriction>
      </xsd:complexContent>
   </xsd:complexType>

   <xsd:complexType name="TipoCinturon_Negro_segundo_Dan">
      <xsd:complexContent>
         <xsd:restriction base="xsd:anyType">
            <xsd:sequence>
               <xsd:element name="Tecnica_Base" type="xsd:string" />
               <xsd:element name="Tecnica_Directa" type="xsd:string" />
               <xsd:element name="Tecnica_Indirecta_Circular" type="xsd:string" />
               <xsd:element name="Tecnica_Pierna" type="xsd:string" />
               <xsd:element name="Tecnica_Combinada" type="xsd:string" />
               <xsd:element name="Teoria" type="xsd:string" />
               <xsd:element name="Kumite" type="xsd:string" />
               <xsd:element name="Kata" type="xsd:string" />
               <xsd:element name="Campeonatos" type="xsd:string" />
               <xsd:element name="Tenica" type="xsd:string" />
               <xsd:element name="Aplicaciones" type="xsd:string" />
               <xsd:element name="Aplicacion_Tecnica" type="xsd:string" />
               <xsd:element name="Demo_Libre" type="xsd:string" />
            </xsd:sequence>
         </xsd:restriction>
      </xsd:complexContent>
   </xsd:complexType>

   <xsd:complexType name="TipoCinturon_Negro_primer_Dan">
      <xsd:complexContent>
         <xsd:restriction base="xsd:anyType">
            <xsd:sequence>
               <xsd:element name="Tecnica_Defensa" type="xsd:string" />
               <xsd:element name="Tecnica_Pierna" type="xsd:string" />
               <xsd:element name="Tecnica_Directa_Indirecta" type="xsd:string" />
               <xsd:element name="Tecnica_Combinada" type="xsd:string" />
               <xsd:element name="Teoria" type="xsd:string" />
               <xsd:element name="Kata" type="xsd:string" />
               <xsd:element name="Kumite" type="xsd:string" />
               <xsd:element name="Aplicacion_Tecnica" type="xsd:string" />
            </xsd:sequence>
         </xsd:restriction>
      </xsd:complexContent>
   </xsd:complexType>

   <xsd:complexType name="Tipocinturon_Negro">
      <xsd:complexContent>
         <xsd:restriction base="xsd:anyType">
            <xsd:sequence>
               <xsd:element name="Tecnica_Directa" type="xsd:string" />
               <xsd:element name="Tecnica_Circulares" type="xsd:string" />
               <xsd:element name="Tecnica_Pierna" type="xsd:string" />
               <xsd:element name="Teoria" type="xsd:string" />
               <xsd:element name="Kata" type="xsd:string" />
               <xsd:element name="Kumite" type="xsd:string" />
            </xsd:sequence>
         </xsd:restriction>
      </xsd:complexContent>
   </xsd:complexType>

   <xsd:complexType name="TipoHasta_3er_Dan">
      <xsd:complexContent>
         <xsd:restriction base="xsd:anyType">
            <xsd:sequence>
               <xsd:element name="Tecnicas" type="xsd:string" />
               <xsd:element name="Kata" type="xsd:string" />
               <xsd:element name="Kumite" type="xsd:string" />
               <xsd:element name="Campeonatos" type="xsd:string" />
            </xsd:sequence>
         </xsd:restriction>
      </xsd:complexContent>
   </xsd:complexType>

   <xsd:complexType name="TipoQuinto_Dan_y_Superior">
      <xsd:complexContent>
         <xsd:restriction base="xsd:anyType">
            <xsd:sequence>
               <xsd:element name="Kata" type="xsd:string" />
               <xsd:element name="Coloquio" type="xsd:string" />
            </xsd:sequence>
         </xsd:restriction>
      </xsd:complexContent>
   </xsd:complexType>

   <xsd:complexType name="TipoSuspende_Examen">
      <xsd:complexContent>
         <xsd:restriction base="xsd:anyType">
            <xsd:sequence>
               <xsd:element name="Id_Aspirante" type="tipoidsuspenso" />
               <xsd:element name="Suspende_Parcial" type="xsd:string" />
               <xsd:element name="Suspende_total" type="xsd:string" />
               <xsd:element name="Suspende_Segunda_Fase" type="xsd:string" />
            </xsd:sequence>
         </xsd:restriction>
      </xsd:complexContent>
   </xsd:complexType>

   <xsd:simpleType name="tipoidsuspenso">
      <xsd:restriction base="xsd:integer">
         <xsd:pattern value="[0-9]{3}"></xsd:pattern>
      </xsd:restriction>
   </xsd:simpleType>










</xsd:schema>

=== Sergi-P/Examen-Final-DDL/Examen.xml
<?xml version="1.0" encoding="utf-8"?>


<?xml-stylesheet href="examen.css"?>


<ExamenFinalDDL xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="examen.xsd">
        
            <Aspirante>
                <Id_Aspirante>001</Id_Aspirante>
                <Nombre>Sergi</Nombre>
                <Apellido>Pifarr√©</Apellido>
                <DNI>47980544z</DNI>   
                <Telefono>123456789</Telefono> 
                <Direccion>c/remolins 33</Direccion>
                <Fecha_Nacimiento>2002-12-22</Fecha_Nacimiento>
                <Dan>1ro</Dan>    
                <Cinturon>negro</Cinturon>   
                <Fecha_Ingreso>2021-12-22</Fecha_Ingreso>  
                <Tiempo_Dan_Anterior>1 mes</Tiempo_Dan_Anterior>  
                <Cuenta_Abonada>Si</Cuenta_Abonada>
            </Aspirante>

            <Fotos>
                <Foto_Dni>Foto_Dni.png</Foto_Dni>  
                <Foto_Carnet_Grado>Foto_Carnet_Grado.png</Foto_Carnet_Grado> 
                <Foto_Aspirante>Foto_Aspirante.png</Foto_Aspirante>  
            </Fotos>

            <Meritos>
                <Id_Aspirante>001</Id_Aspirante>
                <Edad_Aspirante>18</Edad_Aspirante>
                <Licencia_Actualizada>Si</Licencia_Actualizada>
                <Trabajo_Escrito>Si</Trabajo_Escrito>
                
            </Meritos>

            <tribunal>
                <Numero_Jueces>6</Numero_Jueces>
                <Calificacion_Final>5</Calificacion_Final>
                <Id_Aspirante>001</Id_Aspirante>
                <Resultado>Si</Resultado>
                <Dispensa_medica>Si</Dispensa_medica>

            </tribunal>

            <Jueces>
                <id_Jueces>001</id_Jueces>
                <Nombre>Albert</Nombre>
                <Apellido>Gomez</Apellido>
                <Diploma_Juez>Si</Diploma_Juez>   
            </Jueces>

            <Jueces>
                <id_Jueces>002</id_Jueces>
                <Nombre>Albert</Nombre>
                <Apellido>Gomez</Apellido>
                <Diploma_Juez>Si</Diploma_Juez>   
            </Jueces>

            <Jueces>
                <id_Jueces>003</id_Jueces>
                <Nombre>Albert</Nombre>
                <Apellido>Gomez</Apellido>
                <Diploma_Juez>Si</Diploma_Juez>   
            </Jueces>

            <Jueces>
                <id_Jueces>004</id_Jueces>
                <Nombre>Albert</Nombre>
                <Apellido>Gomez</Apellido>
                <Diploma_Juez>Si</Diploma_Juez>   
            </Jueces>

            <Jueces>
                <id_Jueces>005</id_Jueces>
                <Nombre>Albert</Nombre>
                <Apellido>Gomez</Apellido>
                <Diploma_Juez>Si</Diploma_Juez>   
            </Jueces>

            <Jueces>
                <id_Jueces>006</id_Jueces>
                <Nombre>Albert</Nombre>
                <Apellido>Gomez</Apellido>
                <Diploma_Juez>Si</Diploma_Juez>   
            </Jueces>

            

            <Criterio_Valoracion>
                <Indumentaria>5</Indumentaria>
                <Aseo_Personal>5</Aseo_Personal>
                <Ejecucion_Tecnica>5</Ejecucion_Tecnica>
                <Valores>5</Valores>
                <Respuestas>5</Respuestas>
            </Criterio_Valoracion>

            <Cinturon_Negro_Cuarto_Dan>
                <Kumite>apto</Kumite>
                <Kata>apto</Kata>
                <Coloquio>apto</Coloquio>
                <Aplicacion_Tecnica>apto</Aplicacion_Tecnica>
                <Demo_Libre>apto</Demo_Libre>
            </Cinturon_Negro_Cuarto_Dan>
<!-- 
            <Cinturon_Negro_tercer_Dan>
                <Variaciones_tecnica>si</Variaciones_tecnica>
                <Kumite>si</Kumite>
                <Kata>si</Kata>
                <Aplicacion_Tecnica>si</Aplicacion_Tecnica>
                <Teoria>si</Teoria>
                <Campeonatos>si</Campeonatos>
                <Tenica>si</Tenica>
                <Aplicaciones>si</Aplicaciones>
                <Demo_Libre>si</Demo_Libre>
            </Cinturon_Negro_tercer_Dan>

            <Cinturon_Negro_segundo_Dan>
                <Tecnica_Base>si</Tecnica_Base>
                <Tecnica_Directa>si</Tecnica_Directa>
                <Tecnica_Indirecta_Circular>si</Tecnica_Indirecta_Circular>
                <Tecnica_Pierna>si</Tecnica_Pierna>
                <Tecnica_Combinada>si</Tecnica_Combinada>
                <Teoria>si</Teoria>
                <Kumite>si</Kumite>
                <Kata>si</Kata>
                <Campeonatos>si</Campeonatos>
                <Tenica>si</Tenica>
                <Aplicaciones>si</Aplicaciones>
                <Aplicacion_Tecnica>si</Aplicacion_Tecnica>
                <Demo_Libre>si</Demo_Libre>
            </Cinturon_Negro_segundo_Dan>

            <Cinturon_Negro_primer_Dan>
                <Tecnica_Defensa>si</Tecnica_Defensa>
                <Tecnica_Pierna>si</Tecnica_Pierna>
                <Tecnica_Directa_Indirecta>si</Tecnica_Directa_Indirecta>
                <Tecnica_Combinada>si</Tecnica_Combinada>
                <Teoria>si</Teoria>
                <Kata>si</Kata>
                <Kumite>si</Kumite>
                <Aplicacion_Tecnica>si</Aplicacion_Tecnica>
            </Cinturon_Negro_primer_Dan>

            <cinturon_Negro>
                <Tecnica_Directa>si</Tecnica_Directa>
                <Tecnica_Circulares>si</Tecnica_Circulares>
                <Tecnica_Pierna>si</Tecnica_Pierna>
                <Teoria>si</Teoria>
                <Kata>si</Kata>
                <Kumite>si</Kumite>
            </cinturon_Negro>

            <Hasta_3er_Dan>
                <Tecnicas>si</Tecnicas>
                <Kata>si</Kata>
                <Kumite>si</Kumite>
                <Campeonatos>si</Campeonatos>
            </Hasta_3er_Dan>

            <Quinto_Dan_y_Superior>
                <Kata>si</Kata>
                <Coloquio>si</Coloquio>
            </Quinto_Dan_y_Superior>
-->
            <Suspende_Examen>
                <Id_Aspirante>001</Id_Aspirante>
                <Suspende_Parcial>no</Suspende_Parcial>
                <Suspende_total>no</Suspende_total>
                <Suspende_Segunda_Fase>no</Suspende_Segunda_Fase>
            </Suspende_Examen>
</ExamenFinalDDL>
